package com.gamerforea.packetunlimiter;

import static com.gamerforea.packetunlimiter.CoreMod.MODID;
import static com.gamerforea.packetunlimiter.CoreMod.NAME;
import static com.gamerforea.packetunlimiter.CoreMod.VERSION;

import com.google.common.eventbus.EventBus;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;

public final class ModContainer extends DummyModContainer
{
	private final ModMetadata meta = new ModMetadata();

	public ModContainer()
	{
		this.meta.autogenerated = false;
		this.meta.authorList.add("gamerforEA");
		this.meta.credits = "Created by gamerforEA.";
		this.meta.modId = this.getModId();
		this.meta.name = this.getName();
		this.meta.version = this.getVersion();
	}

	@Override
	public boolean registerBus(EventBus bus, LoadController controller)
	{
		return true;
	}

	@Override
	public String getModId()
	{
		return MODID;
	}

	@Override
	public String getName()
	{
		return NAME;
	}

	@Override
	public String getVersion()
	{
		return VERSION;
	}

	@Override
	public String getDisplayVersion()
	{
		return this.getVersion();
	}

	@Override
	public ModMetadata getMetadata()
	{
		return this.meta;
	}
}
